"""Evaluate a label-quality checkpoint on the large set.

Follows the thesis test protocol (Section 8.5), unchanged: the Pascal VOC
2012 training split (5717 images) is the large set; for every image one bad
and one good candidate are generated by the thesis generator (the
evaluation draw of data_loader.Data: good candidates drawn inside the
bands, bad ones 10% from the detectors -- whose final class is decided by
the uncertainty-region metric -- and 90% from the Table 8.2 error types;
none of the training-only sources: no exact-ground-truth share, image-hard
or image-swap negatives, or augmentation). Reports the classification
table, accuracy, weighted F1 and the confusion matrix at threshold 0.5,
and ROC-AUC. The draw depends on --seed, --workers and --batch_size, not on
the network. Loads any network load_model knows (CorrNet, NetSmall).

Example:
    python3 evaluate.py --ckpt artifacts/best_model_refit.pth --out artifacts/eval.json
"""

import argparse
import json
import os
import random

import numpy as np
import torch
from sklearn.metrics import (accuracy_score, confusion_matrix, f1_score,
                             precision_recall_fscore_support, roc_auc_score)

from data_loader import Data
from neural_network import load_model
from train import set_seed, worker_init


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ckpt", default="artifacts/best_model_refit.pth")
    ap.add_argument("--pool",
                    default="~/fiftyone/voc-2012/train/processed_annotations",
                    help="large-set annotation pool (the VOC train split)")
    ap.add_argument("--batch_size", type=int, default=256)
    ap.add_argument("--detector_share", type=float, default=0.1)
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--limit", type=int, default=0, help="images (0 = all)")
    ap.add_argument("--out", default="", help="optional results json path")
    args = ap.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    # load_model builds the variant recorded in the checkpoint; the eval
    # Data keeps the thesis positive draw. Seeding after the model is built
    # keeps the draw independent of the network (building one consumes
    # random numbers, which would otherwise move the loader's worker seeds).
    model = load_model(os.path.expanduser(args.ckpt), device)
    set_seed(args.seed)

    pool_dir = os.path.expanduser(args.pool)
    files = sorted(os.path.join(pool_dir, f) for f in os.listdir(pool_dir)
                   if f.endswith(".npy"))
    files = [f for f in files
             if any(len(v) for v in
                    np.load(f, allow_pickle=True).item().values())]
    random.shuffle(files)
    if args.limit:
        files = files[:args.limit]
    rows = []
    for f in files:
        rows += [(f, 0), (f, 1)]
    print(f"evaluating {args.ckpt} on {len(files)} images "
          f"({len(rows)} candidates)")

    ds = Data(rows, augment=False, detector_share=args.detector_share)
    loader = torch.utils.data.DataLoader(
        ds, batch_size=args.batch_size, shuffle=False,
        num_workers=args.workers, worker_init_fn=worker_init)

    probs, labels = [], []
    with torch.no_grad():
        for img, planes, y in loader:
            img = img.float().to(device)
            planes = planes.float().to(device)
            probs.extend(torch.softmax(model(img, planes), 1)[:, 1]
                         .cpu().tolist())
            labels.extend(y.tolist())

    preds = [int(p >= 0.5) for p in probs]
    prec, rec, f1, support = precision_recall_fscore_support(
        labels, preds, labels=[0, 1], zero_division=0)
    print("\nclass  precision  recall  f1-score  support")
    for k in (0, 1):
        print(f"{k:>5}  {prec[k]:9.2f}  {rec[k]:6.2f}  {f1[k]:8.2f}  "
              f"{support[k]:7d}")
    acc = accuracy_score(labels, preds)
    w_f1 = f1_score(labels, preds, average="weighted")
    auc = roc_auc_score(labels, probs)
    print(f"\naccuracy {acc:.4f}  weighted-F1 {w_f1:.4f}  ROC-AUC {auc:.4f}")
    cm = confusion_matrix(labels, preds)
    print(f"confusion matrix (rows=truth bad/good):\n{cm}")

    if args.out:
        with open(args.out, "w") as f:
            json.dump({"ckpt": args.ckpt, "args": vars(args), "n": len(labels),
                       "accuracy": acc, "weighted_f1": w_f1, "roc_auc": auc,
                       "precision": prec.tolist(), "recall": rec.tolist(),
                       "f1": f1.tolist(), "support": support.tolist(),
                       "confusion_matrix": cm.tolist()}, f, indent=2)
            f.write("\n")
        print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
